### ISSUE TITLE
Change names of the whole project

### ISSUE THREAD

**Issue by vitoravancini** [techindicium/dbt-airflow-monitoring#15]
We started this as an Airflow monitoring project but now we`ve expanded to dags tooling in general.

We should rename specific Airflow names to some dag terminology e.g. change the name of the repo itself from dbt-airflow-monitoring to dbt-dag-monitoring

**Comment by ArturWagner** [comment]
Totally on board with changing the repo name from dbt-airflow-monitoring to dbt-dag-monitoring.

Developing this [feature](https://github.com/techindicium/dbt-airflow-monitoring/commit/5e3b0294f7540a3ce9215c75c88ec972c0000f9f) shows pretty clearly that sticking to just "Airflow" could be confusing.
